# Generated by Django 4.2.16 on 2024-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
